/*
 * File: app/store/BdStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.BdStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Bd'
    ],

    config: {
        data: [
            {
                id: 1,
                nom: 'lucky luke',
                auteur: 'gosciny'
            },
            {
                id: 2,
                nom: 'Asterix',
                auteur: 'herge'
            }
        ],
        model: 'MyApp.model.Bd',
        storeId: 'BdStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        }
    }
});